source: src
repository: centrapay/centrapay.github.io
show_downloads: false
title: Centrapay Docs
kramdown:
  toc_levels: '2,3'
theme: "just-the-docs"
footer_content: "Copyright &copy; 2021 Centrapay"

search_enabled: true
search:
  button: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Centrapay":
    - "https://centrapay.com"

plugins:
  - jekyll-redirect-from
