services:
  app:
    image: node:22-alpine
    init: true
    working_dir: /work
    volumes: [ ".:/work" ]
    command:
      - sh
      - -c
      - yarn dev --host 0.0.0.0
    ports: [ "4321:4321", "24678:24678" ]
    environment:
      - "ENV=development"
  script:
    image: node:22-alpine
    init: true
    working_dir: /work
    stop_signal: SIGKILL
    volumes: [ ".:/work" ]
    command:
      - sh
      - -c
      - |
        echo "
        To execute a script, run:
        docker-compose run script {command}"
