version: "3"

services:
  app:
    image: node:16
    working_dir: /work
    volumes: [ ".:/work" ]
    command:
      - bash
      - -c
      - yarn dev --host 0.0.0.0
    ports: [ "127.0.0.1:3000:3000" ]

  preview:
    image: node:16
    working_dir: /work
    volumes: [ ".:/work" ]
    command:
      - bash
      - -c
      - |
        yarn build
        yarn preview --host 0.0.0.0 --port 5001
    ports: [ "127.0.0.1:5001:5001" ]

  legacy:
    image: ruby:2.7
    working_dir: /work/legacy
    volumes: [ ".:/work" ]
    command: "bundle exec jekyll serve --livereload --host=0.0.0.0"
    ports: [ "4000:4000", "35729:35729" ]
  script:
    image: node:16
    working_dir: /work
    stop_signal: SIGKILL
    volumes: [ ".:/work" ]
    command:
      - bash
      - -c
      - |
        echo "
        To execute a script, run:
        docker-compose run script {command}"
  ruby-script:
    image: ruby:2.7
    working_dir: /work/legacy
    volumes: [ ".:/work" ]
    stop_signal: SIGKILL
    command:
      - bash
      - -c
      - |
        echo "
        To execute a script, run:
        docker-compose run ruby-script {command}"
