openapi: 3.0.0
info:
  title: Centrapay API
  version: 1.0.0

tags:
  - name: payment-requests

paths:
  /api/payment-requests:
    $ref: './endpoints/create-payment-request.yaml'
  /api/payment-requests/{paymentRequestId}:
    $ref: './endpoints/get-payment-request.yaml'
  /api/payment-requests/short-code/{shortCode}:
    $ref: './endpoints/get-payment-request-by-short-code.yaml'
  /api/me/patron-code-payment-request:
    $ref: './endpoints/get-payment-request-by-patron-code.yaml'
  /api/connections/{connectionId}/latest-payment-request:
    $ref: './endpoints/get-payment-request-by-connection-id.yaml'
  /api/payment-requests/external-ref/{externalRef}:
    $ref: './endpoints/list-payment-requests-by-external-ref.yaml'
  /api/payment-requests/{paymentRequestId}/summary:
    $ref: './endpoints/get-payment-request-summary.yaml'
  /api/payment-requests/{paymentRequestId}/pay:
    $ref: './endpoints/pay-payment-request.yaml'
  /api/payment-requests/{paymentRequestId}/refund:
    $ref: './endpoints/refund-payment-request.yaml'
  /api/payment-requests/{paymentRequestId}/void:
    $ref: './endpoints/void-payment-request.yaml'
  /api/payment-requests/{paymentRequestId}/release:
    $ref: './endpoints/release-payment-request.yaml'
  /api/payment-requests/{paymentRequestId}/confirm:
    $ref: './endpoints/confirm-payment-request.yaml'
  /api/payment-activities:
    $ref: './endpoints/list-payment-activities.yaml'
  /api/payment-requests/{paymentRequestId}/activities:
    $ref: './endpoints/list-payment-request-activities.yaml'
  /api/payment-requests/{paymentRequestId}/conditions/{conditionId}/accept:
    $ref: './endpoints/accept-payment-condition.yaml'
  /api/payment-requests/{paymentRequestId}/conditions/{conditionId}/decline:
    $ref: './endpoints/decline-payment-condition.yaml'

components:
  schemas:
    ApiError:
      type: object
      properties:
        message:
          type: string
          description: The error code.
  responses:
    $ref: './models/responses.yaml'
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
