type: object
properties:
  configId:
    type: string
    description: The [Merchant Config](/api/merchant-configs) id used to configure the payment options.

x-examples:
  configId: mc_5efbe2fb96c08357bb2b9242
