name: Deploy Centrapay Docs Dev

on:
  workflow_dispatch

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22
      - run: yarn install --frozen-lock-file
      - run: ./build.sh --mode development
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::450412180052:role/github-actions-centrapay-docs
          role-session-name: centrapay-docs-preview-deploy-session
          aws-region: ap-southeast-1
      - run: ./scripts/deploy-dev.sh
