name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --frozen-lock-file
      - run: yarn lint
      - run: ./build-nuxt-site.sh
      - run: cp CNAME _site
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.JEKYLL_PAT }}
          BRANCH: gh-pages
          FOLDER: _site
