name: Validate Jekyll Site

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: cd new-docs && yarn install --frozen-lock-file
      - run: cd new-docs && yarn lint
      - run: ./build-nuxt-site.sh
