name: Validate Site

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lock-file
      - run: yarn lint
      - run: yarn test
      - run: ./build.sh
      - run: yarn linkinator
      - run: yarn integration
